// Generated by CIRCT unknown git version
module AXI4Buffer_1(	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:37:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:37:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:37:9]
  output        auto_in_aw_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_aw_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_aw_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [36:0] auto_in_aw_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_aw_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_in_aw_bits_burst,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_aw_bits_lock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_aw_bits_cache,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_aw_bits_prot,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_aw_bits_qos,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_aw_bits_echo_real_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_w_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_w_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_in_w_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_in_w_bits_strb,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_w_bits_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_in_b_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_b_bits_resp,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_b_bits_echo_real_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_ar_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_ar_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_ar_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [36:0] auto_in_ar_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_ar_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_in_ar_bits_burst,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_ar_bits_lock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_ar_bits_cache,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_ar_bits_prot,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_ar_bits_qos,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_ar_bits_echo_real_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_r_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_r_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_in_r_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_in_r_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_r_bits_resp,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_r_bits_echo_real_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_r_bits_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_aw_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_aw_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_aw_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [36:0] auto_out_aw_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_aw_bits_echo_real_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_w_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_w_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_out_w_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_out_w_bits_strb,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_b_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_b_bits_echo_real_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_ar_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_ar_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_ar_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [36:0] auto_out_ar_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_ar_bits_echo_real_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_r_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_r_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_r_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_out_r_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_r_bits_echo_real_last	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  Queue2_AXI4BundleAW_1 nodeOut_aw_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_ready               (auto_in_aw_ready),
    .io_enq_valid               (auto_in_aw_valid),
    .io_enq_bits_id             (auto_in_aw_bits_id),
    .io_enq_bits_addr           (auto_in_aw_bits_addr),
    .io_enq_bits_size           (auto_in_aw_bits_size),
    .io_enq_bits_burst          (auto_in_aw_bits_burst),
    .io_enq_bits_lock           (auto_in_aw_bits_lock),
    .io_enq_bits_cache          (auto_in_aw_bits_cache),
    .io_enq_bits_prot           (auto_in_aw_bits_prot),
    .io_enq_bits_qos            (auto_in_aw_bits_qos),
    .io_enq_bits_echo_real_last (auto_in_aw_bits_echo_real_last),
    .io_deq_ready               (auto_out_aw_ready),
    .io_deq_valid               (auto_out_aw_valid),
    .io_deq_bits_id             (auto_out_aw_bits_id),
    .io_deq_bits_addr           (auto_out_aw_bits_addr),
    .io_deq_bits_echo_real_last (auto_out_aw_bits_echo_real_last)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue2_AXI4BundleW_TestHarness_UNIQUIFIED nodeOut_w_deq_q(	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (auto_in_w_ready),
    .io_enq_valid     (auto_in_w_valid),
    .io_enq_bits_data (auto_in_w_bits_data),
    .io_enq_bits_strb (auto_in_w_bits_strb),
    .io_enq_bits_last (auto_in_w_bits_last),
    .io_deq_ready     (auto_out_w_ready),
    .io_deq_valid     (auto_out_w_valid),
    .io_deq_bits_data (auto_out_w_bits_data),
    .io_deq_bits_strb (auto_out_w_bits_strb),
    .io_deq_bits_last (/* unused */)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue2_AXI4BundleB_1 nodeIn_b_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_ready               (auto_out_b_ready),
    .io_enq_valid               (auto_out_b_valid),
    .io_enq_bits_id             (auto_out_b_bits_id),
    .io_enq_bits_echo_real_last (auto_out_b_bits_echo_real_last),
    .io_deq_ready               (auto_in_b_ready),
    .io_deq_valid               (auto_in_b_valid),
    .io_deq_bits_id             (auto_in_b_bits_id),
    .io_deq_bits_resp           (auto_in_b_bits_resp),
    .io_deq_bits_echo_real_last (auto_in_b_bits_echo_real_last)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue2_AXI4BundleAR_1 nodeOut_ar_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_ready               (auto_in_ar_ready),
    .io_enq_valid               (auto_in_ar_valid),
    .io_enq_bits_id             (auto_in_ar_bits_id),
    .io_enq_bits_addr           (auto_in_ar_bits_addr),
    .io_enq_bits_size           (auto_in_ar_bits_size),
    .io_enq_bits_burst          (auto_in_ar_bits_burst),
    .io_enq_bits_lock           (auto_in_ar_bits_lock),
    .io_enq_bits_cache          (auto_in_ar_bits_cache),
    .io_enq_bits_prot           (auto_in_ar_bits_prot),
    .io_enq_bits_qos            (auto_in_ar_bits_qos),
    .io_enq_bits_echo_real_last (auto_in_ar_bits_echo_real_last),
    .io_deq_ready               (auto_out_ar_ready),
    .io_deq_valid               (auto_out_ar_valid),
    .io_deq_bits_id             (auto_out_ar_bits_id),
    .io_deq_bits_addr           (auto_out_ar_bits_addr),
    .io_deq_bits_echo_real_last (auto_out_ar_bits_echo_real_last)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue2_AXI4BundleR_1 nodeIn_r_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_ready               (auto_out_r_ready),
    .io_enq_valid               (auto_out_r_valid),
    .io_enq_bits_id             (auto_out_r_bits_id),
    .io_enq_bits_data           (auto_out_r_bits_data),
    .io_enq_bits_echo_real_last (auto_out_r_bits_echo_real_last),
    .io_deq_ready               (auto_in_r_ready),
    .io_deq_valid               (auto_in_r_valid),
    .io_deq_bits_id             (auto_in_r_bits_id),
    .io_deq_bits_data           (auto_in_r_bits_data),
    .io_deq_bits_resp           (auto_in_r_bits_resp),
    .io_deq_bits_echo_real_last (auto_in_r_bits_echo_real_last),
    .io_deq_bits_last           (auto_in_r_bits_last)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
endmodule

