// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ChipTop(	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  output        uart_0_txd,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         uart_0_rxd,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output        axi4_mem_0_clock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input         axi4_mem_0_bits_aw_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_aw_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [3:0]  axi4_mem_0_bits_aw_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [31:0] axi4_mem_0_bits_aw_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [7:0]  axi4_mem_0_bits_aw_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [2:0]  axi4_mem_0_bits_aw_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [1:0]  axi4_mem_0_bits_aw_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_aw_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [3:0]  axi4_mem_0_bits_aw_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [2:0]  axi4_mem_0_bits_aw_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [3:0]  axi4_mem_0_bits_aw_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input         axi4_mem_0_bits_w_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_w_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [63:0] axi4_mem_0_bits_w_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [7:0]  axi4_mem_0_bits_w_bits_strb,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_w_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_b_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input         axi4_mem_0_bits_b_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input  [3:0]  axi4_mem_0_bits_b_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input  [1:0]  axi4_mem_0_bits_b_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input         axi4_mem_0_bits_ar_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_ar_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [3:0]  axi4_mem_0_bits_ar_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [31:0] axi4_mem_0_bits_ar_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [7:0]  axi4_mem_0_bits_ar_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [2:0]  axi4_mem_0_bits_ar_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [1:0]  axi4_mem_0_bits_ar_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_ar_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [3:0]  axi4_mem_0_bits_ar_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [2:0]  axi4_mem_0_bits_ar_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output [3:0]  axi4_mem_0_bits_ar_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  output        axi4_mem_0_bits_r_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input         axi4_mem_0_bits_r_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input  [3:0]  axi4_mem_0_bits_r_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input  [63:0] axi4_mem_0_bits_r_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input  [1:0]  axi4_mem_0_bits_r_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input         axi4_mem_0_bits_r_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:400:22]
  input         custom_boot,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output        dmi_dmi_req_ready,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         dmi_dmi_req_valid,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  [6:0]  dmi_dmi_req_bits_addr,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  [31:0] dmi_dmi_req_bits_data,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  [1:0]  dmi_dmi_req_bits_op,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         dmi_dmi_resp_ready,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output        dmi_dmi_resp_valid,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output [31:0] dmi_dmi_resp_bits_data,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output [1:0]  dmi_dmi_resp_bits_resp,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         dmi_dmiClock,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         dmi_dmiReset,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output        axi4_mmio_0_clock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input         axi4_mmio_0_bits_aw_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_aw_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [3:0]  axi4_mmio_0_bits_aw_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [37:0] axi4_mmio_0_bits_aw_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [7:0]  axi4_mmio_0_bits_aw_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [2:0]  axi4_mmio_0_bits_aw_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [1:0]  axi4_mmio_0_bits_aw_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_aw_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [3:0]  axi4_mmio_0_bits_aw_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [2:0]  axi4_mmio_0_bits_aw_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [3:0]  axi4_mmio_0_bits_aw_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input         axi4_mmio_0_bits_w_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_w_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [63:0] axi4_mmio_0_bits_w_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [7:0]  axi4_mmio_0_bits_w_bits_strb,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_w_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_b_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input         axi4_mmio_0_bits_b_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input  [3:0]  axi4_mmio_0_bits_b_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input  [1:0]  axi4_mmio_0_bits_b_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input         axi4_mmio_0_bits_ar_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_ar_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [3:0]  axi4_mmio_0_bits_ar_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [37:0] axi4_mmio_0_bits_ar_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [7:0]  axi4_mmio_0_bits_ar_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [2:0]  axi4_mmio_0_bits_ar_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [1:0]  axi4_mmio_0_bits_ar_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_ar_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [3:0]  axi4_mmio_0_bits_ar_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [2:0]  axi4_mmio_0_bits_ar_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output [3:0]  axi4_mmio_0_bits_ar_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  output        axi4_mmio_0_bits_r_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input         axi4_mmio_0_bits_r_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input  [3:0]  axi4_mmio_0_bits_r_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input  [63:0] axi4_mmio_0_bits_r_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input  [1:0]  axi4_mmio_0_bits_r_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input         axi4_mmio_0_bits_r_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:419:22]
  input         reset_io,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:87:24]
  input         clock_uncore,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:95:26]
  output        clock_tap	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
);

  wire        _iocell_dmi_dmi_req_valid_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_addr_6_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_addr_5_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_addr_4_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_addr_3_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_addr_2_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_addr_1_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_addr_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_31_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_30_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_29_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_28_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_27_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_26_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_25_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_24_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_23_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_22_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_21_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_20_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_19_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_18_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_17_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_16_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_15_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_14_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_13_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_12_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_11_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_10_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_9_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_8_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_7_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_6_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_5_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_4_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_3_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_2_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_1_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_data_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_op_1_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_req_bits_op_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_resp_ready_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmi_resp_bits_data_31_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_30_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_29_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_28_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_27_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_26_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_25_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_24_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_23_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_22_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_21_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_20_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_19_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_18_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_17_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_16_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_15_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_14_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_13_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_12_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_11_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_10_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_9_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_8_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_7_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_6_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_5_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_4_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_3_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_2_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_1_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_data_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_resp_1_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmi_resp_bits_resp_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_dmi_dmiClock_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_dmi_dmiReset_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _gated_clock_debug_clock_gate_out;	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
  wire        _dmactiveAck_dmactiveAck_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire        _debug_reset_syncd_debug_reset_sync_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire        _iocell_custom_boot_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_uart_0_rxd_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _system_auto_cbus_fixedClockNode_anon_out_clock;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_auto_cbus_fixedClockNode_anon_out_reset;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_debug_clockeddmi_dmi_req_ready;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_debug_clockeddmi_dmi_resp_valid;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire [31:0] _system_debug_clockeddmi_dmi_resp_bits_data;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire [1:0]  _system_debug_clockeddmi_dmi_resp_bits_resp;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_debug_dmactive;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_uart_0_txd;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_clock_tap;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        debug_reset = ~_debug_reset_syncd_debug_reset_sync_io_q;	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  reg         clock_en;	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
  always @(posedge _system_auto_cbus_fixedClockNode_anon_out_clock or posedge debug_reset) begin	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
    if (debug_reset)	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
      clock_en <= 1'h1;	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
    else	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
      clock_en <= _dmactiveAck_dmactiveAck_io_q;	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    initial begin	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
        clock_en = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
      `endif // RANDOMIZE_REG_INIT
      if (debug_reset)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
        clock_en = 1'h1;	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DigitalTop system (	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore),
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .auto_mbus_fixedClockNode_anon_out_clock                                           (axi4_mem_0_clock),
    .auto_cbus_fixedClockNode_anon_out_clock                                           (_system_auto_cbus_fixedClockNode_anon_out_clock),
    .auto_cbus_fixedClockNode_anon_out_reset                                           (_system_auto_cbus_fixedClockNode_anon_out_reset),
    .auto_sbus_fixedClockNode_anon_out_clock                                           (axi4_mmio_0_clock),
    .resetctrl_hartIsInReset_0                                                         (_system_auto_cbus_fixedClockNode_anon_out_reset),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .debug_clock                                                                       (_gated_clock_debug_clock_gate_out),	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
    .debug_reset                                                                       (debug_reset),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
    .debug_clockeddmi_dmi_req_ready                                                    (_system_debug_clockeddmi_dmi_req_ready),
    .debug_clockeddmi_dmi_req_valid                                                    (_iocell_dmi_dmi_req_valid_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .debug_clockeddmi_dmi_req_bits_addr                                                ({_iocell_dmi_dmi_req_bits_addr_6_i, _iocell_dmi_dmi_req_bits_addr_5_i, _iocell_dmi_dmi_req_bits_addr_4_i, _iocell_dmi_dmi_req_bits_addr_3_i, _iocell_dmi_dmi_req_bits_addr_2_i, _iocell_dmi_dmi_req_bits_addr_1_i, _iocell_dmi_dmi_req_bits_addr_i}),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23, :295:32]
    .debug_clockeddmi_dmi_req_bits_data                                                ({_iocell_dmi_dmi_req_bits_data_31_i, _iocell_dmi_dmi_req_bits_data_30_i, _iocell_dmi_dmi_req_bits_data_29_i, _iocell_dmi_dmi_req_bits_data_28_i, _iocell_dmi_dmi_req_bits_data_27_i, _iocell_dmi_dmi_req_bits_data_26_i, _iocell_dmi_dmi_req_bits_data_25_i, _iocell_dmi_dmi_req_bits_data_24_i, _iocell_dmi_dmi_req_bits_data_23_i, _iocell_dmi_dmi_req_bits_data_22_i, _iocell_dmi_dmi_req_bits_data_21_i, _iocell_dmi_dmi_req_bits_data_20_i, _iocell_dmi_dmi_req_bits_data_19_i, _iocell_dmi_dmi_req_bits_data_18_i, _iocell_dmi_dmi_req_bits_data_17_i, _iocell_dmi_dmi_req_bits_data_16_i, _iocell_dmi_dmi_req_bits_data_15_i, _iocell_dmi_dmi_req_bits_data_14_i, _iocell_dmi_dmi_req_bits_data_13_i, _iocell_dmi_dmi_req_bits_data_12_i, _iocell_dmi_dmi_req_bits_data_11_i, _iocell_dmi_dmi_req_bits_data_10_i, _iocell_dmi_dmi_req_bits_data_9_i, _iocell_dmi_dmi_req_bits_data_8_i, _iocell_dmi_dmi_req_bits_data_7_i, _iocell_dmi_dmi_req_bits_data_6_i, _iocell_dmi_dmi_req_bits_data_5_i, _iocell_dmi_dmi_req_bits_data_4_i, _iocell_dmi_dmi_req_bits_data_3_i, _iocell_dmi_dmi_req_bits_data_2_i, _iocell_dmi_dmi_req_bits_data_1_i, _iocell_dmi_dmi_req_bits_data_i}),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23, :295:32]
    .debug_clockeddmi_dmi_req_bits_op                                                  ({_iocell_dmi_dmi_req_bits_op_1_i, _iocell_dmi_dmi_req_bits_op_i}),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23, :295:32]
    .debug_clockeddmi_dmi_resp_ready                                                   (_iocell_dmi_dmi_resp_ready_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .debug_clockeddmi_dmi_resp_valid                                                   (_system_debug_clockeddmi_dmi_resp_valid),
    .debug_clockeddmi_dmi_resp_bits_data                                               (_system_debug_clockeddmi_dmi_resp_bits_data),
    .debug_clockeddmi_dmi_resp_bits_resp                                               (_system_debug_clockeddmi_dmi_resp_bits_resp),
    .debug_clockeddmi_dmiClock                                                         (_iocell_dmi_dmiClock_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .debug_clockeddmi_dmiReset                                                         (_iocell_dmi_dmiReset_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .debug_dmactive                                                                    (_system_debug_dmactive),
    .debug_dmactiveAck                                                                 (_dmactiveAck_dmactiveAck_io_q),	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .mem_axi4_0_aw_ready                                                               (axi4_mem_0_bits_aw_ready),
    .mem_axi4_0_aw_valid                                                               (axi4_mem_0_bits_aw_valid),
    .mem_axi4_0_aw_bits_id                                                             (axi4_mem_0_bits_aw_bits_id),
    .mem_axi4_0_aw_bits_addr                                                           (axi4_mem_0_bits_aw_bits_addr),
    .mem_axi4_0_aw_bits_len                                                            (axi4_mem_0_bits_aw_bits_len),
    .mem_axi4_0_aw_bits_size                                                           (axi4_mem_0_bits_aw_bits_size),
    .mem_axi4_0_aw_bits_burst                                                          (axi4_mem_0_bits_aw_bits_burst),
    .mem_axi4_0_aw_bits_lock                                                           (axi4_mem_0_bits_aw_bits_lock),
    .mem_axi4_0_aw_bits_cache                                                          (axi4_mem_0_bits_aw_bits_cache),
    .mem_axi4_0_aw_bits_prot                                                           (axi4_mem_0_bits_aw_bits_prot),
    .mem_axi4_0_aw_bits_qos                                                            (axi4_mem_0_bits_aw_bits_qos),
    .mem_axi4_0_w_ready                                                                (axi4_mem_0_bits_w_ready),
    .mem_axi4_0_w_valid                                                                (axi4_mem_0_bits_w_valid),
    .mem_axi4_0_w_bits_data                                                            (axi4_mem_0_bits_w_bits_data),
    .mem_axi4_0_w_bits_strb                                                            (axi4_mem_0_bits_w_bits_strb),
    .mem_axi4_0_w_bits_last                                                            (axi4_mem_0_bits_w_bits_last),
    .mem_axi4_0_b_ready                                                                (axi4_mem_0_bits_b_ready),
    .mem_axi4_0_b_valid                                                                (axi4_mem_0_bits_b_valid),
    .mem_axi4_0_b_bits_id                                                              (axi4_mem_0_bits_b_bits_id),
    .mem_axi4_0_b_bits_resp                                                            (axi4_mem_0_bits_b_bits_resp),
    .mem_axi4_0_ar_ready                                                               (axi4_mem_0_bits_ar_ready),
    .mem_axi4_0_ar_valid                                                               (axi4_mem_0_bits_ar_valid),
    .mem_axi4_0_ar_bits_id                                                             (axi4_mem_0_bits_ar_bits_id),
    .mem_axi4_0_ar_bits_addr                                                           (axi4_mem_0_bits_ar_bits_addr),
    .mem_axi4_0_ar_bits_len                                                            (axi4_mem_0_bits_ar_bits_len),
    .mem_axi4_0_ar_bits_size                                                           (axi4_mem_0_bits_ar_bits_size),
    .mem_axi4_0_ar_bits_burst                                                          (axi4_mem_0_bits_ar_bits_burst),
    .mem_axi4_0_ar_bits_lock                                                           (axi4_mem_0_bits_ar_bits_lock),
    .mem_axi4_0_ar_bits_cache                                                          (axi4_mem_0_bits_ar_bits_cache),
    .mem_axi4_0_ar_bits_prot                                                           (axi4_mem_0_bits_ar_bits_prot),
    .mem_axi4_0_ar_bits_qos                                                            (axi4_mem_0_bits_ar_bits_qos),
    .mem_axi4_0_r_ready                                                                (axi4_mem_0_bits_r_ready),
    .mem_axi4_0_r_valid                                                                (axi4_mem_0_bits_r_valid),
    .mem_axi4_0_r_bits_id                                                              (axi4_mem_0_bits_r_bits_id),
    .mem_axi4_0_r_bits_data                                                            (axi4_mem_0_bits_r_bits_data),
    .mem_axi4_0_r_bits_resp                                                            (axi4_mem_0_bits_r_bits_resp),
    .mem_axi4_0_r_bits_last                                                            (axi4_mem_0_bits_r_bits_last),
    .mmio_axi4_0_aw_ready                                                              (axi4_mmio_0_bits_aw_ready),
    .mmio_axi4_0_aw_valid                                                              (axi4_mmio_0_bits_aw_valid),
    .mmio_axi4_0_aw_bits_id                                                            (axi4_mmio_0_bits_aw_bits_id),
    .mmio_axi4_0_aw_bits_addr                                                          (axi4_mmio_0_bits_aw_bits_addr),
    .mmio_axi4_0_aw_bits_len                                                           (axi4_mmio_0_bits_aw_bits_len),
    .mmio_axi4_0_aw_bits_size                                                          (axi4_mmio_0_bits_aw_bits_size),
    .mmio_axi4_0_aw_bits_burst                                                         (axi4_mmio_0_bits_aw_bits_burst),
    .mmio_axi4_0_aw_bits_lock                                                          (axi4_mmio_0_bits_aw_bits_lock),
    .mmio_axi4_0_aw_bits_cache                                                         (axi4_mmio_0_bits_aw_bits_cache),
    .mmio_axi4_0_aw_bits_prot                                                          (axi4_mmio_0_bits_aw_bits_prot),
    .mmio_axi4_0_aw_bits_qos                                                           (axi4_mmio_0_bits_aw_bits_qos),
    .mmio_axi4_0_w_ready                                                               (axi4_mmio_0_bits_w_ready),
    .mmio_axi4_0_w_valid                                                               (axi4_mmio_0_bits_w_valid),
    .mmio_axi4_0_w_bits_data                                                           (axi4_mmio_0_bits_w_bits_data),
    .mmio_axi4_0_w_bits_strb                                                           (axi4_mmio_0_bits_w_bits_strb),
    .mmio_axi4_0_w_bits_last                                                           (axi4_mmio_0_bits_w_bits_last),
    .mmio_axi4_0_b_ready                                                               (axi4_mmio_0_bits_b_ready),
    .mmio_axi4_0_b_valid                                                               (axi4_mmio_0_bits_b_valid),
    .mmio_axi4_0_b_bits_id                                                             (axi4_mmio_0_bits_b_bits_id),
    .mmio_axi4_0_b_bits_resp                                                           (axi4_mmio_0_bits_b_bits_resp),
    .mmio_axi4_0_ar_ready                                                              (axi4_mmio_0_bits_ar_ready),
    .mmio_axi4_0_ar_valid                                                              (axi4_mmio_0_bits_ar_valid),
    .mmio_axi4_0_ar_bits_id                                                            (axi4_mmio_0_bits_ar_bits_id),
    .mmio_axi4_0_ar_bits_addr                                                          (axi4_mmio_0_bits_ar_bits_addr),
    .mmio_axi4_0_ar_bits_len                                                           (axi4_mmio_0_bits_ar_bits_len),
    .mmio_axi4_0_ar_bits_size                                                          (axi4_mmio_0_bits_ar_bits_size),
    .mmio_axi4_0_ar_bits_burst                                                         (axi4_mmio_0_bits_ar_bits_burst),
    .mmio_axi4_0_ar_bits_lock                                                          (axi4_mmio_0_bits_ar_bits_lock),
    .mmio_axi4_0_ar_bits_cache                                                         (axi4_mmio_0_bits_ar_bits_cache),
    .mmio_axi4_0_ar_bits_prot                                                          (axi4_mmio_0_bits_ar_bits_prot),
    .mmio_axi4_0_ar_bits_qos                                                           (axi4_mmio_0_bits_ar_bits_qos),
    .mmio_axi4_0_r_ready                                                               (axi4_mmio_0_bits_r_ready),
    .mmio_axi4_0_r_valid                                                               (axi4_mmio_0_bits_r_valid),
    .mmio_axi4_0_r_bits_id                                                             (axi4_mmio_0_bits_r_bits_id),
    .mmio_axi4_0_r_bits_data                                                           (axi4_mmio_0_bits_r_bits_data),
    .mmio_axi4_0_r_bits_resp                                                           (axi4_mmio_0_bits_r_bits_resp),
    .mmio_axi4_0_r_bits_last                                                           (axi4_mmio_0_bits_r_bits_last),
    .custom_boot                                                                       (_iocell_custom_boot_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .uart_0_txd                                                                        (_system_uart_0_txd),
    .uart_0_rxd                                                                        (_iocell_uart_0_rxd_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .clock_tap                                                                         (_system_clock_tap)
  );	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  GenericDigitalInIOCell iocell_uart_0_rxd (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (uart_0_rxd),
    .i   (_iocell_uart_0_rxd_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_uart_0_txd (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (uart_0_txd),
    .o   (_system_uart_0_txd),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalInIOCell iocell_custom_boot (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (custom_boot),
    .i   (_iocell_custom_boot_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  AsyncResetSynchronizerShiftReg_w1_d3_i0 debug_reset_syncd_debug_reset_sync (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .reset (_iocell_dmi_dmiReset_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .io_d  (1'h1),	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    .io_q  (_debug_reset_syncd_debug_reset_sync_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  ResetSynchronizerShiftReg_w1_d3_i0 dmactiveAck_dmactiveAck (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .reset (debug_reset),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
    .io_d  (_system_debug_dmactive),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .io_q  (_dmactiveAck_dmactiveAck_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  EICG_wrapper gated_clock_debug_clock_gate (	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
    .in      (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .test_en (1'h0),	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    .en      (clock_en),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
    .out     (_gated_clock_debug_clock_gate_out)
  );	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
  GenericDigitalInIOCell iocell_dmi_dmiReset (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmiReset),
    .i   (_iocell_dmi_dmiReset_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmiClock (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmiClock),
    .i   (_iocell_dmi_dmiClock_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_resp (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_resp_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_resp[0]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_resp_1 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_resp_1_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_resp[1]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[0]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_1 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_1_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[1]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_2 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_2_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[2]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_3 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_3_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[3]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_4 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_4_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[4]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_5 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_5_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[5]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_6 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_6_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[6]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_7 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_7_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[7]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_8 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_8_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[8]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_9 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_9_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[9]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_10 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_10_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[10]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_11 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_11_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[11]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_12 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_12_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[12]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_13 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_13_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[13]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_14 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_14_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[14]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_15 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_15_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[15]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_16 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_16_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[16]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_17 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_17_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[17]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_18 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_18_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[18]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_19 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_19_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[19]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_20 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_20_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[20]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_21 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_21_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[21]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_22 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_22_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[22]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_23 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_23_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[23]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_24 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_24_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[24]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_25 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_25_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[25]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_26 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_26_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[26]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_27 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_27_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[27]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_28 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_28_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[28]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_29 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_29_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[29]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_30 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_30_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[30]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_bits_data_31 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_dmi_dmi_resp_bits_data_31_pad),
    .o   (_system_debug_clockeddmi_dmi_resp_bits_data[31]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_dmi_dmi_resp_valid (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (dmi_dmi_resp_valid),
    .o   (_system_debug_clockeddmi_dmi_resp_valid),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalInIOCell iocell_dmi_dmi_resp_ready (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_resp_ready),
    .i   (_iocell_dmi_dmi_resp_ready_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_op (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_op[0]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_op_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_op_1 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_op[1]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_op_1_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[0]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_1 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[1]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_1_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_2 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[2]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_2_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_3 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[3]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_3_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_4 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[4]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_4_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_5 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[5]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_5_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_6 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[6]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_6_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_7 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[7]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_7_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_8 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[8]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_8_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_9 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[9]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_9_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_10 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[10]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_10_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_11 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[11]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_11_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_12 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[12]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_12_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_13 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[13]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_13_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_14 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[14]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_14_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_15 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[15]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_15_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_16 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[16]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_16_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_17 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[17]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_17_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_18 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[18]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_18_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_19 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[19]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_19_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_20 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[20]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_20_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_21 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[21]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_21_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_22 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[22]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_22_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_23 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[23]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_23_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_24 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[24]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_24_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_25 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[25]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_25_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_26 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[26]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_26_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_27 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[27]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_27_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_28 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[28]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_28_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_29 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[29]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_29_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_30 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[30]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_30_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_data_31 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_data[31]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_data_31_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_addr (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_addr[0]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_addr_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_addr_1 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_addr[1]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_addr_1_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_addr_2 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_addr[2]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_addr_2_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_addr_3 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_addr[3]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_addr_3_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_addr_4 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_addr[4]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_addr_4_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_addr_5 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_addr[5]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_addr_5_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_bits_addr_6 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_bits_addr[6]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_dmi_dmi_req_bits_addr_6_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_dmi_dmi_req_valid (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (dmi_dmi_req_valid),
    .i   (_iocell_dmi_dmi_req_valid_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_dmi_dmi_req_ready (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (dmi_dmi_req_ready),
    .o   (_system_debug_clockeddmi_dmi_req_ready),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_clock_tap (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (clock_tap),
    .o   (_system_clock_tap),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  assign dmi_dmi_resp_bits_data = {_iocell_dmi_dmi_resp_bits_data_31_pad, _iocell_dmi_dmi_resp_bits_data_30_pad, _iocell_dmi_dmi_resp_bits_data_29_pad, _iocell_dmi_dmi_resp_bits_data_28_pad, _iocell_dmi_dmi_resp_bits_data_27_pad, _iocell_dmi_dmi_resp_bits_data_26_pad, _iocell_dmi_dmi_resp_bits_data_25_pad, _iocell_dmi_dmi_resp_bits_data_24_pad, _iocell_dmi_dmi_resp_bits_data_23_pad, _iocell_dmi_dmi_resp_bits_data_22_pad, _iocell_dmi_dmi_resp_bits_data_21_pad, _iocell_dmi_dmi_resp_bits_data_20_pad, _iocell_dmi_dmi_resp_bits_data_19_pad, _iocell_dmi_dmi_resp_bits_data_18_pad, _iocell_dmi_dmi_resp_bits_data_17_pad, _iocell_dmi_dmi_resp_bits_data_16_pad, _iocell_dmi_dmi_resp_bits_data_15_pad, _iocell_dmi_dmi_resp_bits_data_14_pad, _iocell_dmi_dmi_resp_bits_data_13_pad, _iocell_dmi_dmi_resp_bits_data_12_pad, _iocell_dmi_dmi_resp_bits_data_11_pad, _iocell_dmi_dmi_resp_bits_data_10_pad, _iocell_dmi_dmi_resp_bits_data_9_pad, _iocell_dmi_dmi_resp_bits_data_8_pad, _iocell_dmi_dmi_resp_bits_data_7_pad, _iocell_dmi_dmi_resp_bits_data_6_pad, _iocell_dmi_dmi_resp_bits_data_5_pad, _iocell_dmi_dmi_resp_bits_data_4_pad, _iocell_dmi_dmi_resp_bits_data_3_pad, _iocell_dmi_dmi_resp_bits_data_2_pad, _iocell_dmi_dmi_resp_bits_data_1_pad, _iocell_dmi_dmi_resp_bits_data_pad};	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24, :312:31]
  assign dmi_dmi_resp_bits_resp = {_iocell_dmi_dmi_resp_bits_resp_1_pad, _iocell_dmi_dmi_resp_bits_resp_pad};	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24, :312:31]
endmodule

