// Generated by CIRCT unknown git version
module mem_0(	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  input  [33:0] R0_addr,
  input         R0_en,
  input         R0_clk,
  output [63:0] R0_data,
  input  [33:0] W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [63:0] W0_data,
  input  [7:0]  W0_mask
);

  mem_0_ext mem_0_ext (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (W0_en),
    .W0_clk  (W0_clk),
    .W0_data (W0_data),
    .W0_mask (W0_mask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
endmodule

