// Generated by CIRCT unknown git version

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module TestHarness(	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7]
  input  clock,	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7]
  input  reset,	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7]
  output io_success	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:20:14]
);

  wire        _source_1_clk;	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  wire        _source_clk;	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  wire        _harnessBinderReset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire        _mmio_mem_io_axi4_0_aw_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_w_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_b_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [3:0]  _mmio_mem_io_axi4_0_b_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [1:0]  _mmio_mem_io_axi4_0_b_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_ar_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_r_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [3:0]  _mmio_mem_io_axi4_0_r_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [63:0] _mmio_mem_io_axi4_0_r_bits_data;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [1:0]  _mmio_mem_io_axi4_0_r_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_r_bits_last;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _TestchipSimDTM_debug_req_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
  wire [6:0]  _TestchipSimDTM_debug_req_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
  wire [31:0] _TestchipSimDTM_debug_req_bits_data;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
  wire [1:0]  _TestchipSimDTM_debug_req_bits_op;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
  wire        _TestchipSimDTM_debug_resp_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
  wire [31:0] _TestchipSimDTM_exit;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
  wire        _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        _simdram_axi_aw_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_w_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_b_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [3:0]  _simdram_axi_b_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [1:0]  _simdram_axi_b_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_ar_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_r_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [3:0]  _simdram_axi_r_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [63:0] _simdram_axi_r_bits_data;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [1:0]  _simdram_axi_r_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_r_bits_last;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _uart_sim_0_uartno0_io_uart_rxd;	// @[generators/testchipip/src/main/scala/uart/SimUART.scala:76:28]
  wire        _chiptop0_uart_0_txd;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_clock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_aw_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [31:0] _chiptop0_axi4_mem_0_bits_aw_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_aw_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_aw_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mem_0_bits_aw_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_aw_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_aw_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_w_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [63:0] _chiptop0_axi4_mem_0_bits_w_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_w_bits_strb;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_w_bits_last;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_b_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_ar_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [31:0] _chiptop0_axi4_mem_0_bits_ar_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_ar_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_ar_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mem_0_bits_ar_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_ar_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_ar_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_r_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_dmi_dmi_req_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_dmi_dmi_resp_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [31:0] _chiptop0_dmi_dmi_resp_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_dmi_dmi_resp_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_clock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_aw_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [37:0] _chiptop0_axi4_mmio_0_bits_aw_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_aw_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_w_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [63:0] _chiptop0_axi4_mmio_0_bits_w_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mmio_0_bits_w_bits_strb;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_w_bits_last;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_b_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_ar_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [37:0] _chiptop0_axi4_mmio_0_bits_ar_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_ar_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_r_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  `ifndef SYNTHESIS	// @[generators/testchipip/src/main/scala/soc/SimDTM.scala:25:11]
    always @(posedge _source_1_clk) begin	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26, generators/testchipip/src/main/scala/soc/SimDTM.scala:25:11]
      if (~_harnessBinderReset_catcher_io_sync_reset & (|(_TestchipSimDTM_exit[31:1]))) begin	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21, generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28, generators/testchipip/src/main/scala/soc/SimDTM.scala:25:{11,20,72}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/testchipip/src/main/scala/soc/SimDTM.scala:25:11]
          $error("Assertion failed: *** FAILED *** (exit code = %d)\n\n    at SimDTM.scala:25 assert(io.exit < 2.U, \"*** FAILED *** (exit code = %%%%d)\\n\", io.exit >> 1.U)\n", {1'h0, _TestchipSimDTM_exit[31:1]});	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21, generators/testchipip/src/main/scala/soc/SimDTM.scala:25:{11,72}]
        if (`STOP_COND_)	// @[generators/testchipip/src/main/scala/soc/SimDTM.scala:25:11]
          $fatal;	// @[generators/testchipip/src/main/scala/soc/SimDTM.scala:25:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  ChipTop chiptop0 (	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .uart_0_txd                     (_chiptop0_uart_0_txd),
    .uart_0_rxd                     (_uart_sim_0_uartno0_io_uart_rxd),	// @[generators/testchipip/src/main/scala/uart/SimUART.scala:76:28]
    .axi4_mem_0_clock               (_chiptop0_axi4_mem_0_clock),
    .axi4_mem_0_bits_aw_ready       (_simdram_axi_aw_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_aw_valid       (_chiptop0_axi4_mem_0_bits_aw_valid),
    .axi4_mem_0_bits_aw_bits_id     (_chiptop0_axi4_mem_0_bits_aw_bits_id),
    .axi4_mem_0_bits_aw_bits_addr   (_chiptop0_axi4_mem_0_bits_aw_bits_addr),
    .axi4_mem_0_bits_aw_bits_len    (_chiptop0_axi4_mem_0_bits_aw_bits_len),
    .axi4_mem_0_bits_aw_bits_size   (_chiptop0_axi4_mem_0_bits_aw_bits_size),
    .axi4_mem_0_bits_aw_bits_burst  (_chiptop0_axi4_mem_0_bits_aw_bits_burst),
    .axi4_mem_0_bits_aw_bits_lock   (_chiptop0_axi4_mem_0_bits_aw_bits_lock),
    .axi4_mem_0_bits_aw_bits_cache  (_chiptop0_axi4_mem_0_bits_aw_bits_cache),
    .axi4_mem_0_bits_aw_bits_prot   (_chiptop0_axi4_mem_0_bits_aw_bits_prot),
    .axi4_mem_0_bits_aw_bits_qos    (_chiptop0_axi4_mem_0_bits_aw_bits_qos),
    .axi4_mem_0_bits_w_ready        (_simdram_axi_w_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_w_valid        (_chiptop0_axi4_mem_0_bits_w_valid),
    .axi4_mem_0_bits_w_bits_data    (_chiptop0_axi4_mem_0_bits_w_bits_data),
    .axi4_mem_0_bits_w_bits_strb    (_chiptop0_axi4_mem_0_bits_w_bits_strb),
    .axi4_mem_0_bits_w_bits_last    (_chiptop0_axi4_mem_0_bits_w_bits_last),
    .axi4_mem_0_bits_b_ready        (_chiptop0_axi4_mem_0_bits_b_ready),
    .axi4_mem_0_bits_b_valid        (_simdram_axi_b_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_b_bits_id      (_simdram_axi_b_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_b_bits_resp    (_simdram_axi_b_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_ar_ready       (_simdram_axi_ar_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_ar_valid       (_chiptop0_axi4_mem_0_bits_ar_valid),
    .axi4_mem_0_bits_ar_bits_id     (_chiptop0_axi4_mem_0_bits_ar_bits_id),
    .axi4_mem_0_bits_ar_bits_addr   (_chiptop0_axi4_mem_0_bits_ar_bits_addr),
    .axi4_mem_0_bits_ar_bits_len    (_chiptop0_axi4_mem_0_bits_ar_bits_len),
    .axi4_mem_0_bits_ar_bits_size   (_chiptop0_axi4_mem_0_bits_ar_bits_size),
    .axi4_mem_0_bits_ar_bits_burst  (_chiptop0_axi4_mem_0_bits_ar_bits_burst),
    .axi4_mem_0_bits_ar_bits_lock   (_chiptop0_axi4_mem_0_bits_ar_bits_lock),
    .axi4_mem_0_bits_ar_bits_cache  (_chiptop0_axi4_mem_0_bits_ar_bits_cache),
    .axi4_mem_0_bits_ar_bits_prot   (_chiptop0_axi4_mem_0_bits_ar_bits_prot),
    .axi4_mem_0_bits_ar_bits_qos    (_chiptop0_axi4_mem_0_bits_ar_bits_qos),
    .axi4_mem_0_bits_r_ready        (_chiptop0_axi4_mem_0_bits_r_ready),
    .axi4_mem_0_bits_r_valid        (_simdram_axi_r_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_id      (_simdram_axi_r_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_data    (_simdram_axi_r_bits_data),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_resp    (_simdram_axi_r_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_last    (_simdram_axi_r_bits_last),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .custom_boot                    (_plusarg_reader_out),	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .dmi_dmi_req_ready              (_chiptop0_dmi_dmi_req_ready),
    .dmi_dmi_req_valid              (_TestchipSimDTM_debug_req_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
    .dmi_dmi_req_bits_addr          (_TestchipSimDTM_debug_req_bits_addr),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
    .dmi_dmi_req_bits_data          (_TestchipSimDTM_debug_req_bits_data),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
    .dmi_dmi_req_bits_op            (_TestchipSimDTM_debug_req_bits_op),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
    .dmi_dmi_resp_ready             (_TestchipSimDTM_debug_resp_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
    .dmi_dmi_resp_valid             (_chiptop0_dmi_dmi_resp_valid),
    .dmi_dmi_resp_bits_data         (_chiptop0_dmi_dmi_resp_bits_data),
    .dmi_dmi_resp_bits_resp         (_chiptop0_dmi_dmi_resp_bits_resp),
    .dmi_dmiClock                   (_source_1_clk),	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .dmi_dmiReset                   (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .axi4_mmio_0_clock              (_chiptop0_axi4_mmio_0_clock),
    .axi4_mmio_0_bits_aw_ready      (_mmio_mem_io_axi4_0_aw_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_aw_valid      (_chiptop0_axi4_mmio_0_bits_aw_valid),
    .axi4_mmio_0_bits_aw_bits_id    (_chiptop0_axi4_mmio_0_bits_aw_bits_id),
    .axi4_mmio_0_bits_aw_bits_addr  (_chiptop0_axi4_mmio_0_bits_aw_bits_addr),
    .axi4_mmio_0_bits_aw_bits_len   (_chiptop0_axi4_mmio_0_bits_aw_bits_len),
    .axi4_mmio_0_bits_aw_bits_size  (_chiptop0_axi4_mmio_0_bits_aw_bits_size),
    .axi4_mmio_0_bits_aw_bits_burst (_chiptop0_axi4_mmio_0_bits_aw_bits_burst),
    .axi4_mmio_0_bits_aw_bits_lock  (_chiptop0_axi4_mmio_0_bits_aw_bits_lock),
    .axi4_mmio_0_bits_aw_bits_cache (_chiptop0_axi4_mmio_0_bits_aw_bits_cache),
    .axi4_mmio_0_bits_aw_bits_prot  (_chiptop0_axi4_mmio_0_bits_aw_bits_prot),
    .axi4_mmio_0_bits_aw_bits_qos   (_chiptop0_axi4_mmio_0_bits_aw_bits_qos),
    .axi4_mmio_0_bits_w_ready       (_mmio_mem_io_axi4_0_w_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_w_valid       (_chiptop0_axi4_mmio_0_bits_w_valid),
    .axi4_mmio_0_bits_w_bits_data   (_chiptop0_axi4_mmio_0_bits_w_bits_data),
    .axi4_mmio_0_bits_w_bits_strb   (_chiptop0_axi4_mmio_0_bits_w_bits_strb),
    .axi4_mmio_0_bits_w_bits_last   (_chiptop0_axi4_mmio_0_bits_w_bits_last),
    .axi4_mmio_0_bits_b_ready       (_chiptop0_axi4_mmio_0_bits_b_ready),
    .axi4_mmio_0_bits_b_valid       (_mmio_mem_io_axi4_0_b_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_b_bits_id     (_mmio_mem_io_axi4_0_b_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_b_bits_resp   (_mmio_mem_io_axi4_0_b_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_ar_ready      (_mmio_mem_io_axi4_0_ar_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_ar_valid      (_chiptop0_axi4_mmio_0_bits_ar_valid),
    .axi4_mmio_0_bits_ar_bits_id    (_chiptop0_axi4_mmio_0_bits_ar_bits_id),
    .axi4_mmio_0_bits_ar_bits_addr  (_chiptop0_axi4_mmio_0_bits_ar_bits_addr),
    .axi4_mmio_0_bits_ar_bits_len   (_chiptop0_axi4_mmio_0_bits_ar_bits_len),
    .axi4_mmio_0_bits_ar_bits_size  (_chiptop0_axi4_mmio_0_bits_ar_bits_size),
    .axi4_mmio_0_bits_ar_bits_burst (_chiptop0_axi4_mmio_0_bits_ar_bits_burst),
    .axi4_mmio_0_bits_ar_bits_lock  (_chiptop0_axi4_mmio_0_bits_ar_bits_lock),
    .axi4_mmio_0_bits_ar_bits_cache (_chiptop0_axi4_mmio_0_bits_ar_bits_cache),
    .axi4_mmio_0_bits_ar_bits_prot  (_chiptop0_axi4_mmio_0_bits_ar_bits_prot),
    .axi4_mmio_0_bits_ar_bits_qos   (_chiptop0_axi4_mmio_0_bits_ar_bits_qos),
    .axi4_mmio_0_bits_r_ready       (_chiptop0_axi4_mmio_0_bits_r_ready),
    .axi4_mmio_0_bits_r_valid       (_mmio_mem_io_axi4_0_r_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_id     (_mmio_mem_io_axi4_0_r_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_data   (_mmio_mem_io_axi4_0_r_bits_data),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_resp   (_mmio_mem_io_axi4_0_r_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_last   (_mmio_mem_io_axi4_0_r_bits_last),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .reset_io                       (reset),
    .clock_uncore                   (_source_clk),	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .clock_tap                      (/* unused */)
  );	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  UARTAdapter uart_sim_0_uartno0 (	// @[generators/testchipip/src/main/scala/uart/SimUART.scala:76:28]
    .clock       (_source_1_clk),	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .reset       (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_uart_txd (_chiptop0_uart_0_txd),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_uart_rxd (_uart_sim_0_uartno0_io_uart_rxd)
  );	// @[generators/testchipip/src/main/scala/uart/SimUART.scala:76:28]
  SimDRAM #(
    .ADDR_BITS(32),
    .CHIP_ID(0),
    .CLOCK_HZ(500000000),
    .DATA_BITS(64),
    .ID_BITS(4),
    .LINE_SIZE(64),
    .MEM_BASE(40'd2147483648),
    .MEM_SIZE(268435456)
  ) simdram (	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .clock             (_chiptop0_axi4_mem_0_clock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .reset             (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .axi_aw_ready      (_simdram_axi_aw_ready),
    .axi_aw_valid      (_chiptop0_axi4_mem_0_bits_aw_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_id    (_chiptop0_axi4_mem_0_bits_aw_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_addr  (_chiptop0_axi4_mem_0_bits_aw_bits_addr),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_len   (_chiptop0_axi4_mem_0_bits_aw_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_size  (_chiptop0_axi4_mem_0_bits_aw_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_burst (_chiptop0_axi4_mem_0_bits_aw_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_lock  (_chiptop0_axi4_mem_0_bits_aw_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_cache (_chiptop0_axi4_mem_0_bits_aw_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_prot  (_chiptop0_axi4_mem_0_bits_aw_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_qos   (_chiptop0_axi4_mem_0_bits_aw_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_ready       (_simdram_axi_w_ready),
    .axi_w_valid       (_chiptop0_axi4_mem_0_bits_w_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_bits_data   (_chiptop0_axi4_mem_0_bits_w_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_bits_strb   (_chiptop0_axi4_mem_0_bits_w_bits_strb),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_bits_last   (_chiptop0_axi4_mem_0_bits_w_bits_last),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_b_ready       (_chiptop0_axi4_mem_0_bits_b_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_b_valid       (_simdram_axi_b_valid),
    .axi_b_bits_id     (_simdram_axi_b_bits_id),
    .axi_b_bits_resp   (_simdram_axi_b_bits_resp),
    .axi_ar_ready      (_simdram_axi_ar_ready),
    .axi_ar_valid      (_chiptop0_axi4_mem_0_bits_ar_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_id    (_chiptop0_axi4_mem_0_bits_ar_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_addr  (_chiptop0_axi4_mem_0_bits_ar_bits_addr),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_len   (_chiptop0_axi4_mem_0_bits_ar_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_size  (_chiptop0_axi4_mem_0_bits_ar_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_burst (_chiptop0_axi4_mem_0_bits_ar_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_lock  (_chiptop0_axi4_mem_0_bits_ar_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_cache (_chiptop0_axi4_mem_0_bits_ar_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_prot  (_chiptop0_axi4_mem_0_bits_ar_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_qos   (_chiptop0_axi4_mem_0_bits_ar_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_r_ready       (_chiptop0_axi4_mem_0_bits_r_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_r_valid       (_simdram_axi_r_valid),
    .axi_r_bits_id     (_simdram_axi_r_bits_id),
    .axi_r_bits_data   (_simdram_axi_r_bits_data),
    .axi_r_bits_resp   (_simdram_axi_r_bits_resp),
    .axi_r_bits_last   (_simdram_axi_r_bits_last)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  plusarg_reader_TestHarness_UNIQUIFIED #(
    .DEFAULT(0),
    .FORMAT("custom_boot_pin=%d"),
    .WIDTH(1)
  ) plusarg_reader(	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  TestchipSimDTM TestchipSimDTM (	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
    .clk                  (_source_1_clk),	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .reset                (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .debug_req_ready      (_chiptop0_dmi_dmi_req_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .debug_req_valid      (_TestchipSimDTM_debug_req_valid),
    .debug_req_bits_addr  (_TestchipSimDTM_debug_req_bits_addr),
    .debug_req_bits_data  (_TestchipSimDTM_debug_req_bits_data),
    .debug_req_bits_op    (_TestchipSimDTM_debug_req_bits_op),
    .debug_resp_ready     (_TestchipSimDTM_debug_resp_ready),
    .debug_resp_valid     (_chiptop0_dmi_dmi_resp_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .debug_resp_bits_data (_chiptop0_dmi_dmi_resp_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .debug_resp_bits_resp (_chiptop0_dmi_dmi_resp_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .exit                 (_TestchipSimDTM_exit)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21]
  SimAXIMem mmio_mem (	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .clock                   (_chiptop0_axi4_mmio_0_clock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .reset                   (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_axi4_0_aw_ready      (_mmio_mem_io_axi4_0_aw_ready),
    .io_axi4_0_aw_valid      (_chiptop0_axi4_mmio_0_bits_aw_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_id    (_chiptop0_axi4_mmio_0_bits_aw_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_addr  (_chiptop0_axi4_mmio_0_bits_aw_bits_addr[36:0]),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:159:27, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_len   (_chiptop0_axi4_mmio_0_bits_aw_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_size  (_chiptop0_axi4_mmio_0_bits_aw_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_burst (_chiptop0_axi4_mmio_0_bits_aw_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_lock  (_chiptop0_axi4_mmio_0_bits_aw_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_cache (_chiptop0_axi4_mmio_0_bits_aw_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_prot  (_chiptop0_axi4_mmio_0_bits_aw_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_qos   (_chiptop0_axi4_mmio_0_bits_aw_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_ready       (_mmio_mem_io_axi4_0_w_ready),
    .io_axi4_0_w_valid       (_chiptop0_axi4_mmio_0_bits_w_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_bits_data   (_chiptop0_axi4_mmio_0_bits_w_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_bits_strb   (_chiptop0_axi4_mmio_0_bits_w_bits_strb),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_bits_last   (_chiptop0_axi4_mmio_0_bits_w_bits_last),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_b_ready       (_chiptop0_axi4_mmio_0_bits_b_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_b_valid       (_mmio_mem_io_axi4_0_b_valid),
    .io_axi4_0_b_bits_id     (_mmio_mem_io_axi4_0_b_bits_id),
    .io_axi4_0_b_bits_resp   (_mmio_mem_io_axi4_0_b_bits_resp),
    .io_axi4_0_ar_ready      (_mmio_mem_io_axi4_0_ar_ready),
    .io_axi4_0_ar_valid      (_chiptop0_axi4_mmio_0_bits_ar_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_id    (_chiptop0_axi4_mmio_0_bits_ar_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_addr  (_chiptop0_axi4_mmio_0_bits_ar_bits_addr[36:0]),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:159:27, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_len   (_chiptop0_axi4_mmio_0_bits_ar_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_size  (_chiptop0_axi4_mmio_0_bits_ar_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_burst (_chiptop0_axi4_mmio_0_bits_ar_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_lock  (_chiptop0_axi4_mmio_0_bits_ar_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_cache (_chiptop0_axi4_mmio_0_bits_ar_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_prot  (_chiptop0_axi4_mmio_0_bits_ar_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_qos   (_chiptop0_axi4_mmio_0_bits_ar_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_r_ready       (_chiptop0_axi4_mmio_0_bits_r_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_r_valid       (_mmio_mem_io_axi4_0_r_valid),
    .io_axi4_0_r_bits_id     (_mmio_mem_io_axi4_0_r_bits_id),
    .io_axi4_0_r_bits_data   (_mmio_mem_io_axi4_0_r_bits_data),
    .io_axi4_0_r_bits_resp   (_mmio_mem_io_axi4_0_r_bits_resp),
    .io_axi4_0_r_bits_last   (_mmio_mem_io_axi4_0_r_bits_last)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  ResetCatchAndSync_d3_TestHarness_UNIQUIFIED harnessBinderReset_catcher(	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_source_1_clk),	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .reset         (reset),
    .io_sync_reset (_harnessBinderReset_catcher_io_sync_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  ClockSourceAtFreqMHz #(
    .PERIOD(2.000000e+00)
  ) source (	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .power (1'h1),	// @[generators/testchipip/src/main/scala/soc/SimDTM.scala:25:11]
    .gate  (1'h0),
    .clk   (_source_clk)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  ClockSourceAtFreqMHz #(
    .PERIOD(1.000000e+01)
  ) source_1 (	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .power (1'h1),	// @[generators/testchipip/src/main/scala/soc/SimDTM.scala:25:11]
    .gate  (1'h0),
    .clk   (_source_1_clk)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  assign io_success = _TestchipSimDTM_exit == 32'h1;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:200:21, generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7, generators/testchipip/src/main/scala/soc/SimDTM.scala:24:26]
endmodule

